### ISSUE TITLE
MTA Deployment is not working

### ISSUE THREAD

**Issue by rbhuva** [cloudfoundry-incubator/multiapps-controller#869]
### Description
We are trying to deploy MTA application but got an error :- com.sap.cloud.lm.sl.common.SLException: Error detecting deployed MTA: Controller operation failed: 400 Bad Request: CF-BadQueryParameter(10005): The query parameter is invalid: Unknown query parameter(s): 'label_selector' 

### Your environment
*           MultiApps Controller version -  Built from master branch of MultiApp Controller date 3rd June
*             which CF vendor is used - We have deployed open source cf in Azure.
*             which backing services are used  - PostgreSQL

### Steps to reproduce
Tell us how to reproduce this issue.
We are trying to deploy our first hello world MTA Application on our cf environment.

### Additional information

Operation log is here in below link.
https://gist.github.com/rbhuva/75452b34e51980fed4df5bae33f9b0ca

**Comment by theghost5800** [comment]
Hello @rbhuva ,

As I can see, the issue is similar to this one https://cloudfoundry.slack.com/archives/C9V0Z8ZPF/p1590689601000300 . It looks like your CF Controller is too old and doesn't support CF metadata in v3 of controller. You have to update your CF Controller to the latest version of you want to use our latest version of Deploy Service.
